# Usamos imagen oficial de PyTorch con soporte para CUDA 11.8
FROM pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime

WORKDIR /app

# Copia los archivos del proyecto
COPY . .

# Actualiza pip e instala dependencias
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

ENV PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

# Define punto de entrada opcional
CMD ["python", "scripts/train.py"]
